services:
  - type: web
    name: portfolio-optimization-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
    rootDir: backend
    region: singapore